FROM microsoft/dotnet:1.1.1-sdk-nanoserver
WORKDIR /app
EXPOSE 80

# copy csproj and restore as distinct layers
COPY app/webapplication.csproj ./
RUN dotnet restore -r win10-x64

# copy and build everything else
COPY app ./
RUN dotnet publish -c release -o out -r win10-x64