FROM microsoft/dotnet:1.1.1-sdk-nanoserver
WORKDIR /app

# copy csproj and restore as distinct layers
COPY app/webapplication.csproj ./
RUN dotnet restore

# copy and build everything else
COPY app ./
RUN dotnet publish -c release -o out